### ISSUE TITLE
openSUSE

### ISSUE THREAD

**Issue by vKnmnn** [aguslr/multibootusb#108]
it seems like the standard iso names have changed for tumbleweed. multiusb's config does not recognize the tumbleweed iso (downloaded 2017-08-21).
leap is not recognized as well. i have not tried the net-installer yet.

**Comment by aguslr** [comment]
Hi @vKnmnn!

The ISO names have not changed, it's just that only the [Tumbleweed's Live ISOs](http://download.opensuse.org/tumbleweed/iso/) are bootable.

The installation ISOs for both Leap and Tumbleweed cannot find the installation media so they only work if they can download the packages from the internet. This is far from ideal but I will add support for them (both DVD and NET ISO files) anyway.

**Comment by vKnmnn** [comment]
I see, i may have gotten my hands on a snapshot release. those should still be recognized, i think.
What do you mean, only tumbleweed is bootable? By means of loopback booting with grub, i suppose?

when not findind install media, i found out that its possible, most of the times, to manually mount the appropriate FS with the correct path. We might be able to manipulate this in the suse.cfg, so all images will work.

**Comment by aguslr** [comment]
> What do you mean, only tumbleweed is bootable?

Sorry, I meant that only the **Live** ISO files for Tumbleweed are bootable using our project files at the moment.

I will add support for the installation ISO files (DVD and NET) but it'd be great if we found a way to mount the appropriate filesystem as you said, instead of having to use the network to download the packages.

**Comment by aguslr** [comment]
> it'd be great if we found a way to mount the appropriate filesystem as you said

Actually, scratch that! It seems [that adding `install=hd:$iso_path`](https://wiki.archlinux.org/index.php?title=Multiboot_USB_drive&oldid=483842#openSUSE) will do the trick. I don't know how I missed that. :smile:

**Comment by vKnmnn** [comment]
yeah, i had something like that in mind. nice to see it working.
