### ISSUE TITLE
Support for SuperGRUBdisk

### ISSUE THREAD

**Issue by vKnmnn** [aguslr/multibootusb#111]
Please add support for this ISO, as it's realy useful if one messed up their bootloader. it supports EFI and BIOS.
i guess SuperGRUB's options could alspo be incorporated directly into the first level of multibootusb as a general first aid measure
[SuperGRUB disk](
http://www.supergrubdisk.org/super-grub2-disk/)

**Comment by vKnmnn** [comment]
Hey, just wanted to tell you:
Supergrubdisk has a loopback detection, so i unpacked it and added it manually.
I integrated the supergrub disk via mbusb.cfg.local, by adding to the file:
```
submenu "Super Grub Disk 2 -> " {
    source $prefix/supergrub/grub.cfg
}
```
After that i copied the contents of the super grub iso /boot/grub/ to the supergrub folder.

**Comment by aguslr** [comment]
Hey @vKnmnn! Did you check #115? Doesn't this work for you? You don't need to copy the contents of the ISO file since it's loaded automatically.

**Comment by vKnmnn** [comment]
I have tried #115, but as i said, Supergrub Disk 2 has a loopmount detection. When booted via ISO, it shows a message, that this mode is not supported.

**Comment by aguslr** [comment]
Oh, I see what you mean now.

Yes, using `loopback.cfg` displays that warning message, but it then loads `grub.cfg` just like your workaround does. We could load `grub.cfg` directly and avoid the message but I think that it should be displayed as intended.

I admit I haven't tested it much. Is there anything that works with your workaround (copying the contents of the ISO file) that doesn't work with #115?

**Comment by vKnmnn** [comment]
i cannot do much testing on my computer, but everything seems to be working.
i wonder why the dev has chosen to prompt that warning then.

**Comment by aguslr** [comment]
> i wonder why the dev has chosen to prompt that warning then.

Yes, me too. Maybe some people have reported issues when using it like this. Still, we have to respect their wishes and keep the warning.
