### ISSUE TITLE
USB boots into GRUB command line instead of GRUB image boot menu.

### ISSUE THREAD

**Issue by Clae224** [aguslr/multibootusb#118]
I loaded up four images into one 16 GB USB that I have used before as a live USB and it booted straight into the GRUB command line instead of the boot select screen. Just to be certain this wasn't a distro-specific image problem, I removed all of the distros and placed an ubuntu 17.04 image as the only image on the USB with no persistence, and I was still landing on the Grub command line. 

I'm using 8.8.0 on Win10. 

Sorry if I'm missing something obvious.

**Comment by aguslr** [comment]
Hi @Clae224,

As I understand, this is an USB drive that already had GRUB installed, right? Did you add the [relevant code] (http://mbusb.aguslr.com/install.html#adding-to-existing-usb-drive) to the existing `grub.cfg` and copied the files?

> I'm using 8.8.0 on Win10.

What does this mean? I'm sorry, I'm just not too versed in Windows. :sweat_smile:

**Comment by Clae224** [comment]
Didn't see that guide. I'll try again in a few days when I have time.

8.8.0 was just the version of multibootusb I was using.

**Comment by aguslr** [comment]
> 8.8.0 was just the version of multibootusb I was using.

Well, this is awkward... Since we don't have versions, I think this issue was meant for [mbusb/multibootusb](https://github.com/mbusb/multibootusb).

I mean, I don't blame you at all, the names are very similar and I have been meaning to change it. Sorry for that! :smiley:
