### ISSUE TITLE
Debian: No common CD-ROM drive was detected

### ISSUE THREAD

**Issue by thorsummoner** [aguslr/multibootusb#124]
Heya, I wondered @aguslr, it looks like you added the debian grub loader options, have you used them successfully before? The boot loader works as far as getting the iso's menu items, but it seems to fail on debian's installer which seems to rely heavily on /cdrom.

Can you give me any leads on how I might be able to over come this limitation? Another multiboot usb project has this [in their bug tracker](https://github.com/mbusb/multibootusb/issues/85), though I don't really follow how their workarounds are supposed to work - and as such, i'm kinda feeling stuck.

Thank you!

**Comment by aguslr** [comment]
Hey @thorsummoner! It's true that the installation doesn't work (only the Live environment does) so I should probably add a note regarding this. Same thing happens with Ubuntu ISOs.

There is a way to make it work (see #40) although, if you have a network connection during the installation, I would recommend using [Debian Network boot](https://www.debian.org/distrib/netinst) instead. Just download the `mini.iso` ([amd64](http://ftp.nl.debian.org/debian/dists/stretch/main/installer-amd64/current/images/netboot/) or [i386](http://ftp.nl.debian.org/debian/dists/stretch/main/installer-i386/current/images/netboot/)) and rename it to something like `debian-mini.iso` so it's detected by GRUB.

As an alternative, you can also use some iPXE disk like [netboot.xyz](https://netboot.xyz/) that allows you to install many different operating systems. Just get the ISO and copy it to your pendrive's `/boot/isos` directory.

**Comment by vKnmnn** [comment]
There is a lengthy discussion on this [here](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=724931)
It's been almost four years since that Patch has been filed and we're talking about Debian here, so it's not likely to be included in D10, I'd say. Patching the ISO in grub doesn't seem like the way to go, so another option remains to be:
using the hd-media initrd, as described in the bugreport i linked.

**Comment by thorsummoner** [comment]
I think Linux Mint Debian Edition (lmde-*.iso) files have this fault as well, although their boot error is masked and I forgot to get specific details on it. I'm going to play with the vmlinuz and initrd.gz workarround for debian as well as lmde now that I understand it better.

**Comment by aguslr** [comment]
@thorsummoner, I am closing this issue for now since it depends on Debian and there is nothing we can do here.
