### ISSUE TITLE
Support for archbang

### ISSUE THREAD

**Issue by star-ter-js** [aguslr/multibootusb#125]
please add support for [archbang](https://www.google.it/url?sa=t&rct=j&q=&esrc=s&source=web&cd=4&cad=rja&uact=8&ved=0ahUKEwjqvaTM8fzWAhWLK1AKHXbKAWsQFgg-MAM&url=https%3A%2F%2Fsourceforge.net%2Fprojects%2Farchbang%2F&usg=AOvVaw3WiE9SiOjLa8V1JNmRV2CU)

**Comment by aguslr** [comment]
Hey @star-ter-js! I've added support for ArchBang in #126.
