### ISSUE TITLE
Support memtest86 (Passmark version)

### ISSUE THREAD

**Issue by vamega** [aguslr/multibootusb#141]
Just attempted to use [this image](https://www.memtest86.com/downloads/memtest86-usb.tar.gz) from their website and it wasn't picked up.

**Comment by vamega** [comment]
I think I made a mistake yesterday. That file is an img file, and not an iso file. I'll both try converting it to an iso file, as well as trying the bin file from their website too see if either of those options work, and will report back.

**Comment by aguslr** [comment]
Hi @vamega!

If you check [our project's page for Memtest86](http://mbusb.aguslr.com/misc/memtest86.html), you can see that only the ISO and binary from <http://www.memtest.org> work. You can make the ISO from <http://www.memtest86.com> work if you rename it to something like `memtest86-7.4.iso`.

> That file is an img file, and not an iso file.

Indeed, that USB image file won't work, but the downloadable ISO should work.

**Comment by vamega** [comment]
So the iso from http://memtest96.com works, however it seems like it only works when booting in BIOS mode?

Is it possible to use memdisk to chainload the UEFI executable on an iso? I noticed that this was the case with `netboot.xyz` as well.

**Comment by aguslr** [comment]
Commit 3017e3a should have fixed this.

**Comment by blling** [comment]
What is the final solution? The latest `memtest86` does not have a `ISO` image :(
