### ISSUE TITLE
Kali Linux 2017.3 not working

### ISSUE THREAD

**Issue by Mattze96** [aguslr/multibootusb#190]
`kali-linux-2017.3-amd64.iso` is not working with the current release

![image](https://user-images.githubusercontent.com/3738126/34535585-a314aee8-f0c2-11e7-8c59-03c2ce6d43bf.png)

**Comment by ZeTriUm** [comment]
Now check. It work.

**Comment by Mattze96** [comment]
I was only testing in qemu as stated in #191 
I adapted your suggested qemu-test command
