### ISSUE TITLE
keep config directory consistent with prefix of iso files

### ISSUE THREAD

**Issue by vKnmnn** [aguslr/multibootusb#196]
i noticed, that some config directories differ from the names of their respective ISO files, eg. `arch.d` and `archlinux-*.iso` or `android-x86.d`, while no other dir has the architecture in it's name.

This makes globbing harder than it needs be.

Can we agree on naming the folders according to the first word in the ISO?

**Comment by aguslr** [comment]
Good point, @vKnmnn
