### ISSUE TITLE
Anarchy Linux now replaces Arch Anywhere

### ISSUE THREAD

**Issue by BruceZhang1993** [aguslr/multibootusb#197]
According to [this news](https://anarchy-linux.org/news/Anarchy-Linux-replaces-Arch-Anywhere/), Anarchy Linux now replaces Arch Anywhere

The arch-anywhere cfg need modification.
ISO filename matches anarchy-*.iso

Also, [this web page](http://mbusb.aguslr.com/isos.html) need to change home link & download link from arch-anywhere.org to anarchy-linux.org.

**Comment by P0ly** [comment]
Thanks for the note @BruceZhang1993!
I added and tested the new Anarchy Linux configs and kept the Arch Anywhere grub configs for compatibility. But should the broken links of Arch Anywhere be removed or replaced with the ones of Anarchy Linux? @aguslr

**Comment by BruceZhang1993** [comment]
@P0ly Thanks for #200 
Does the Anarchy Linux config work for both of cli and gui version?

**Comment by P0ly** [comment]
@BruceZhang1993 Yes, both versions are booting(i did not test the install, but it should work too).

**Comment by aguslr** [comment]
Fixed by #200.
