### ISSUE TITLE
Hanging at 99% and leaves the partition unuseable

### ISSUE THREAD

**Issue by AncalagonTheBlack** [aguslr/multibootusb#199]
On Linux Mint 18.3 X64 the installer hangs at 99% and leaves the usb drive unuseable

**Comment by P0ly** [comment]
Hello @AncalagonTheBlack,
I am not sure if this project could cause this anyhow.
To make things clear, could you try again and "burn" the iso image to your usb with(everything on the device will be deleted, so be careful):

`dd if=</path/to/linux-mint.iso> of=/dev/<your usb device>`

or

if you are not so in command lines you can try [Etcher](https://etcher.io/).

If this happens again, I think you should open an issue by the Linux Mint Community instead.

**Comment by AncalagonTheBlack** [comment]
Well this works but it wont help to create a multiboot stick. But thanks for your work. The Problem is the first 99% go really fast before it starts to hang

**Comment by probonopd** [comment]
> Why you guys have the same name ?

See https://github.com/aguslr/multibootusb/issues/194
