### ISSUE TITLE
Support Slax Linux

### ISSUE THREAD

**Issue by jmalenko** [aguslr/multibootusb#2]
Added Slax Linux. The patch is attached.

Notes:
1. I used English-US variant
2. There are actually 16 items in the menu of the original Slax, That is because they unclude all 16 combinations of 4 binary kernel flags. I include only 6 items: all four flags enabled, none of the four flags enabled, one item for each flag enabled.
3. Due to too many items, I have a submenu for each Slax Variant (eg. "Slax (32 bit}" and "Slax (64 bit}") which is different from the approach in Ubuntu, where all the variants are under one menu "Ubuntu".

[slax.zip](https://github.com/aguslr/multibootusb/files/434523/slax.zip)

**Comment by aguslr** [comment]
Hey Jaromír,

Thanks for the patch. Unfortunately, it doesn't seem to work for me. Am I missing something?

Also, I cannot import the patch into my Git repo as it's missing a valid email address. Could you maybe fork my repo in GitHub and send a Pull Request instead? That should make it easier for me to merge the patch.

Cheers.

**Comment by jmalenko** [comment]
Hi Agus,

I created the patch with
`git diff --cached > slax.patch`

I believe the following should work
`git apply slax.patch`

I read the GitHub manual about submitting changes. However, forking is too complicated for me because:
1. the changes would need to be manually transfered from the directory where is the clone of your repo to the forked one
2. the manual is not specific about removing the fork. When may I remove it? I don't intend to keep it.

**Comment by aguslr** [comment]
Hi Jaromír,

I added and tested the patch. Thanks!
