### ISSUE TITLE
Script and manually failing at Installing GRUB for BIOS (am running from ubuntu-gnome 16.10)

### ISSUE THREAD

**Issue by annfry** [aguslr/multibootusb#20]
I'm having an issue attempting to do this manually, as well as being stuck when running your script. The script fails at: Installing GRUB for BIOS on /dev/sda... FAILED. When following the Arch linux page Multiboot usb drive, I get stuck at the same spot where it is saying to use the following command: 
grub-install --target=i386-pc --boot-directory=/DATA_MOUNTPOINT/boot --recheck /dev/sda
the error I get is: 
grub-install: error: /usr/lib/grub/i386-pc/modinfo.sh doesn't exist. Please specify --target or --directory.

What am I doing incorrectly?

Thanks for the script!

**Comment by Huby1** [comment]
Hi annfry,

Read the issue #7 I think it will answer your issue.

**Comment by annfry** [comment]
Huby1 Thanks, it turned out that I had to install the grub2 package, I then re-ran the script, and everything works now.

**Comment by annfry** [comment]
Unfortunately, the installation of grub2 fixed the previous fail message, now i'm getting the same error message as what was in issue #7, but something different in the log files. The error message in the log files now says: Installing for x86_64-efi platform.
Installing for x86_64-efi platform.
/usr/sbin/grub-install: error: cannot open `/mnt/MBU-DATA/boot/grub/x86_64-efi/loadenv.mod': Read-only file system.

Unfortunately I've already checked to ensure I've installed the extra package, but now I'm not sure what to do.

**Comment by aguslr** [comment]
Hi annfry,

`/usr/sbin/grub-install: error: cannot open '/mnt/MBU-DATA/boot/grub/x86_64-efi/loadenv.mod': Read-only file system`

That error seems to imply that the USB device was mounted read-only and it cannot write the files to it. If this keeps happening, there might be a problem with the device or another process is mounting it read-only automatically.

Also, thanks to @Huby1 for jumping in to help on the first issue.

**Comment by annfry** [comment]
hi aguslr, 
It works! It only took me a couple of times of writing over the contents of the usb keys that I've got, so when the script ever returned failed lines, I would use gparted to change the partition table type, then I would run dd with if=/dev/zero. Eventually I finally got the script to run successfully, now I'm just wondering if I can add additional distribution grub entries. For example I have isos for ubuntu server, and edubuntu that I would like to load (as well as many others). By the way I was confused about whether I had to add individual entries into grub, but then tried the key and found the .cfg files that were included with grub. That could be noted in the readme that you don't have to do anything other than copy the isos to the iso directory for the grub configs you've included as I was confused about that at the start.

**Comment by annfry** [comment]
I have created a .cfg file for ubuntu server, however when booting, it bypasses the first menu - do you know how to make it boot to that first menu or is that the install media's grub menu, and you can't boot to it, but you can make more entries in grub to boot to those different options?

if [ -e $isopath/ubuntu-16.10-server*.iso ]; then
  submenu "Ubuntu 16.10 Server->" {
    if [ -e "$isopath/ubuntu-16.10-server-i386.iso" ]; then
      set isofile32="$isopath/ubuntu-16.10-server-i386.iso"
      loopback loop32 $isofile32
      set gfxpayload=keep
      menuentry "Install Ubuntu Server (32 bit)" {
        bootoptions="iso-scan/filename=$isofile32 file=/cdrom/preseed/ubuntu.seed splash quiet --"
        linux (loop32)/install/vmlinuz $bootoptions
        initrd (loop32)/install/initrd.gz
      }
    fi
    if cpuid -l ; then # Check whether CPU is 64-bit
      if [ -e "$isopath/ubuntu-16.10-server-amd64.iso" ]; then
        set isofile64="$isopath/ubuntu-16.10-server-amd64.iso"
        loopback loop64 $isofile64
        set gfxpayload=keep
        menuentry "Install Ubuntu Server (64 bit)" {
          bootoptions="iso-scan/filename=$isofile64 file=/cdrom/preseed/ubuntu.seed splash quiet --"
          linux (loop64)/install/vmlinuz $bootoptions
          initrd (loop64)/install/initrd.gz
        }
      fi
    fi
  }
fi

**Comment by aguslr** [comment]
Hi again Ann,

> I have created a .cfg file for ubuntu server, however when booting, it bypasses the first menu - do you know how to make it boot to that first menu or is that the install media's grub menu, and you can't boot to it, but you can make more entries in grub to boot to those different options?

I don't quite understand what you mean. I've tested your configuration and was able to boot the Ubuntu Server installation. However, it fails when it tries to [detect and mount the CD-ROM](http://askubuntu.com/questions/128995/grub2-loopback-booting-ubuntu-server-iso).

This is what I used:
```
if [ -e $isopath/ubuntu-16.10*-server*.iso ]; then
  submenu "Ubuntu 16.10 Server->" {
    if [ -e "$isopath/ubuntu-16.10-server-i386.iso" ]; then
      set isofile32="$isopath/ubuntu-16.10-server-i386.iso"
      loopback loop32 $isofile32
      set gfxpayload=keep
      menuentry "Install Ubuntu Server (32 bit)" {
        bootoptions="iso-scan/filename=$isofile32 file=/cdrom/preseed/ubuntu-server.seed vga=788 quiet --"
        linux (loop32)/install/vmlinuz $bootoptions
        initrd (loop32)/install/initrd.gz
      }
    fi
    if cpuid -l ; then # Check whether CPU is 64-bit
      if [ -e "$isopath/ubuntu-16.10-server-amd64.iso" ]; then
        set isofile64="$isopath/ubuntu-16.10-server-amd64.iso"
        loopback loop64 $isofile64
        set gfxpayload=keep
        menuentry "Install Ubuntu Server (64 bit)" {
          bootoptions="iso-scan/filename=$isofile64 file=/cdrom/preseed/ubuntu-server.seed vga=788 quiet --"
          linux (loop64)/install/vmlinuz $bootoptions
          initrd (loop64)/install/initrd.gz
        }
      fi
    fi
  }
fi
```
