### ISSUE TITLE
Error I386

### ISSUE THREAD

**Issue by danelsan** [aguslr/multibootusb#206]
I run 

makeUSB.sh

but with this error:

# Install GRUB for BIOS
$grub_cmd --force --target=i386-pc \
    --boot-directory="${data_mnt}/${data_subdir}" --recheck "$usb_dev" \
    || cleanUp 10
/usr/sbin/grub-install: errore: /usr/lib/grub/i386-pc/modinfo.sh doesn't exist. Please specify --target or --directory.

Thanks

**Comment by danelsan** [comment]
Sorry, i founded the reply

installed this tools

sudo apt install grub-pc

**Comment by aguslr** [comment]
@sferra, installing the *-bin* packages doesn't affect the installation as the only provide the different targets. If we want to use `--target=x86_64-efi` we will need the package *grub-efi-amd64-bin*, and for `--target=i386-pc` we need *grub-pc-bin*.

Now, if we used BIOS/Legacy boot during the installation of the OS, *grub-pc* and therefore *grub-pc-bin* will be installed. If we used EFI boot, then *grub-efi-amd64* and *grub-efi-amd64-bin* will be installed instead.

**Comment by sferra** [comment]
Thanks for the insight. It would be very nice to have those hints when the script fails as the solution is buried in a growing heap of resolved issues, with an obscure title.

**Comment by aguslr** [comment]
With eb5ac7e018729035b78778efc40fba86a754152a I've added a note to the documentation. Hopefully that'll do.
