### ISSUE TITLE
Keeping both new and old version of SystemRescueCD

### ISSUE THREAD

**Issue by moocan** [aguslr/multibootusb#251]
Hello,

First, many thanks for your work.

I would like to know if it's possible to change inside the `sysrescuecd.d/generic.cfg` the detection of iso file name to keep both old version (systemrescuecd-x86-x.y.z.iso) and new version (systemrescuecd-x.y.z.iso) because some old tools does not exists anymore in new version.

I have added in my multiboot usb key a `sysrescuecd.d/generic-x86.cfg` with `for isofile in $isopath/systemrescuecd-x86-*.iso` with old config file entries and modified the `sysrescuecd.d/generic.cfg` with `for isofile in $isopath/systemrescuecd-*.*.*.iso`.

Is it possible to make it better in case of update with your work ?

Kind Regards

**Comment by aguslr** [comment]
Hey @moocan! That is a very reasonable request. I didn't realize how many of the tools were remove from the new releases. I'll add support for the old files.

**Comment by moocan** [comment]
Hello,

Just to say thanks you.

Kr,
