### ISSUE TITLE
Add support for gparted 27 and amd64

### ISSUE THREAD

**Issue by longtomjr** [aguslr/multibootusb#29]
I do not know how much of an issue this is, but it is an enchantment at least.

 I have limited experience with grub2 configs and the grub conf already there is a bit messy. I might try to unpack the iso to see what is in there.

**Comment by P0ly** [comment]
Hello, it doesn't seem to be an issue.
Using the old config file and adjusting the path to the iso, just works.

**Comment by aguslr** [comment]
It seems #37 fixed this.
