### ISSUE TITLE
makeUSB.sh failed by not finding /usr/lib/grub/x86_64-efi/modinfo.sh

### ISSUE THREAD

**Issue by alex-tu-cc** [aguslr/multibootusb#33]
os: Ubuntu xeinal 16.04
Lagacy BIOS with MBR
the command I executed:
$ sudo ./makeUSB.sh -l -b -e /dev/sdc
Because I try to create a USB disk which have multiple hybrid MBR and UEFI compatible(can be booted with UEFI)
So which package I could find that file under x86_64-efi?

[makeUSB.log.txt](https://github.com/aguslr/multibootusb/files/690455/makeUSB.log.txt)

**Comment by aguslr** [comment]
Hi alex-tu-cc,

For Ubuntu Xenial, you need to install the package [grub-efi-amd64-bin](http://packages.ubuntu.com/xenial/grub-efi-amd64-bin).

**Comment by sferra** [comment]
Issue #206 seems to be related to this one.
