### ISSUE TITLE
add Tiny Core Linux to README

### ISSUE THREAD

**Issue by P0ly** [aguslr/multibootusb#38]
Hi, 
already created a pull request for the support of Tiny Core Linux
and just asking to make an entry for it in the "Get bootable files"-section.

**Comment by P0ly** [comment]
Pull request is #36 btw.

**Comment by P0ly** [comment]
Link to [Tiny Core Linux ](http://tinycorelinux.net/)

**Comment by P0ly** [comment]
PR in #36

**Comment by aguslr** [comment]
Fixed by PR #36, thanks.
