### ISSUE TITLE
problem booting CentOS

### ISSUE THREAD

**Issue by alcir** [aguslr/multibootusb#46]
![screenshot from 2017-01-13 12-03-45](https://cloud.githubusercontent.com/assets/3286123/21927958/787737d4-d988-11e6-9d01-8c391730a06e.png)

**Comment by aguslr** [comment]
Hey @alcir, thanks for bringing this to my attention. Commit 48e69c4 should've fixed the issue.

**Comment by alcir** [comment]
Thank you, now it works like a charm.
