### ISSUE TITLE
makeUSB.sh fails on openSUSE

### ISSUE THREAD

**Issue by dawnbreak** [aguslr/multibootusb#49]
I use openSUSE Tumbleweed and makeUSB.sh fails, because it can not use grub-install. It exists, but got replaced by openSUSE. I had to change it to grub2-install which seems to work.

**Comment by aguslr** [comment]
If `grub-install` exists, what does it do? Shouldn't it be a symlink to `grub2-install`?

I just checked in an openSUSE Tumbleweed LiveCD and `grub-install` doesn't exist. This causes the script to try `grub2-install` so it should work.

**Comment by XavierMarchena** [comment]
Well in my case the script did not tried grub2-install. It just failed. I changed it to only call grub2-install instead and it worked. I am on openSUSE Leap 42.2

**Comment by XavierMarchena** [comment]
Isn't it related to the warning output of the `grub-install` command that reaches the makeUSB script? I am not really familiar with how a shell script behaves on a case like that.

**Comment by aguslr** [comment]
@dawnbreak, @XavierMarchena, I see. I guess the only viable solution is to check for `grub2-install` first and then fallback to `grub-install`.

Should've been fixed with 4020f97. Try it out, please and confirm it works fine.
