### ISSUE TITLE
makeUSB.sh and manual method fails on copyiong files

### ISSUE THREAD

**Issue by jottunn** [aguslr/multibootusb#51]
sudo ./makeUSB.sh --efi -l /dev/sdb ext4
Are you sure you want to use /dev/sdb? [y/N] y
THIS WILL DELETE ALL DATA ON THE DEVICE. Are you sure? [y/N] y
Removing partitions from /dev/sdb... OK
Creating GUID Partition Table on /dev/sdb... OK
Creating BIOS boot partition on /dev/sdb... OK
Creating EFI System partition on /dev/sdb... OK
Creating data partition on /dev/sdb... OK
Setting bootable flag on /dev/sdb3... OK
Formatting BIOS boot partition on /dev/sdb1... OK
Formatting EFI System partition on /dev/sdb2... OK
Formatting data partition as ext4 on /dev/sdb3... OK
Mounting EFI System partition on /mnt/MBU-EFI/... OK
Mounting data partition on /mnt/MBU-DATA/... OK
Installing GRUB for EFI on /dev/sdb... OK
Unmounting EFI System partition on /mnt/MBU-EFI/... OK
Installing GRUB for BIOS on /dev/sdb... OK
Installing fallback GRUB on /dev/sdb3... OK
Creating directories on /mnt/MBU-DATA/boot... OK
Copying files to /mnt/MBU-DATA/boot... FAILED

also manual method fails at:
`cp -rf {grub.cfg,grub.d,multiboot.*} $mntusb/boot/grub/`
since there don't seem to be any targets for `multiboot.*` for copy

am i doing something wrong?

**Comment by aguslr** [comment]
Hi @jottunn!

No you didn't do anything wrong. I deleted the `multiboot.*` placeholder in a4525b7 and forgot to update the instructions and the script.

I fixed it with 66222dc.
