### ISSUE TITLE
Formatting failes

### ISSUE THREAD

**Issue by bertalanimre** [aguslr/multibootusb#52]
Hi Agus,

I'm pretty sure this is just a minor issue and I'M missing something but can you tell me what could go wrong at formatting the pendrive I wish to use? I'm on Fedora 25.

[root@workstation multibootusb] # ./makeUSB.sh /dev/sdc1

```
Are you sure you want to use /dev/sdc1? [y/N] y
THIS WILL DELETE ALL DATA ON THE DEVICE. Are you sure? [y/N] y
Removing partitions from /dev/sdc1... OK
Creating GUID Partition Table on /dev/sdc1... OK
Creating BIOS boot partition on /dev/sdc1... OK
Creating data partition on /dev/sdc1... OK
Setting bootable flag on /dev/sdc12... OK
Formatting BIOS boot partition on /dev/sdc11... OK
Formatting data partition as vfat on /dev/sdc12... FAILED
```

Also if I wish to add custom ISO files, then how exactly I'm supposed to do that?

**Comment by bertalanimre** [comment]
Uops, forgot the log file. Sorry:

[root@workstation multibootusb] # cat makeUSB.log 
```
Warning: The kernel is still using the old partition table.
The new table will be used at the next reboot or after you
run partprobe(8) or kpartx(8)
GPT data structures destroyed! You may now partition the disk using fdisk or
other utilities.
Creating new GPT entries.
Warning: The kernel is still using the old partition table.
The new table will be used at the next reboot or after you
run partprobe(8) or kpartx(8)
The operation has completed successfully.
Setting name!
partNum is 0
REALLY setting name!
Warning: The kernel is still using the old partition table.
The new table will be used at the next reboot or after you
run partprobe(8) or kpartx(8)
The operation has completed successfully.
Setting name!
partNum is 1
REALLY setting name!
Warning: The kernel is still using the old partition table.
The new table will be used at the next reboot or after you
run partprobe(8) or kpartx(8)
The operation has completed successfully.
Setting name!
partNum is 2
REALLY setting name!
Warning: The kernel is still using the old partition table.
The new table will be used at the next reboot or after you
run partprobe(8) or kpartx(8)
The operation has completed successfully.
Warning: The kernel is still using the old partition table.
The new table will be used at the next reboot or after you
run partprobe(8) or kpartx(8)
The operation has completed successfully.
1+0 beolvasott rekord
1+0 kiírt rekord
1048576 bájt (1,0 MB, 1,0 MiB) másolva, 0,00148915 s, 704 MB/s
mkfs.vfat: unable to open /dev/sdc12: No such file or directory
mkfs.fat 4.1 (2017-01-24)
```

Some translations:
1+0 beolvasott rekord = 1+0 read record
1+0 kiírt rekord = 1+0 written record
bájt = byte
másolva = copied

**Comment by P0ly** [comment]
Hi @bertalanimre,
with `/dev/sdc1` you specified only a partition on the device, but you need the whole device!
Try `/dev/sdc` without a number instead.

**Comment by P0ly** [comment]
To add an ISO, simple put it in the `/boot/isos` folder.
You can checkout the `grub.d` folder to see if your linux distribution is supported.
If the name is in there, then it is supported ;).

**Comment by aguslr** [comment]
Hey @bertalanimre,

What was said (thanks @P0ly!) is correct, you need to pass a device, not a partition, to the script.

Also, to add a custom ISO, meaning one that is not already supported, please check [the how-to](http://mbusb.aguslr.com/howto.html) and [submit a pull request](http://mbusb.aguslr.com/contrib.html) if you get it working.

**Comment by bertalanimre** [comment]
I'm a dumbass. Thanks for the notice. Now I just have to get back to my computer and start using tha app. Thanks a lot! :)
