### ISSUE TITLE
directory creation of /mnt/MBU-EFI fails, read-only filesystem

### ISSUE THREAD

**Issue by Clifspeare** [aguslr/multibootusb#53]
I followed the instructions for preparing the drive, then makeUSB.sh fails like this:
https://gist.github.com/Clifspeare/9801bd30c6b2fc7c1c24e11fde193081

**Comment by aguslr** [comment]
Hello @Clifspeare,

`mkdir: cannot create directory ‘/mnt/MBU-EFI/’: Read-only file system`

It seems  that the partition that contains `/mnt` is read-only. Can you create `/mnt/MBU-EFI/` manually as root? Also, what is the output of the command `mount`?
