### ISSUE TITLE
Can't boot memdisk in HP InsydeH2O® UEFI BIOS F.68

### ISSUE THREAD

**Issue by gitterliu** [aguslr/multibootusb#56]
I'm trying to get these two debian isos boot through memdisk :
[firmware-testing-amd64-netinst.iso](http://cdimage.debian.org/cdimage/unofficia/non-free/cd-including-firmware/weekly-builds/amd64/iso-cd)
```
linux16 $prefix/memdisk iso raw
initrd16 /boot/isos/firmware-testing-amd64-netinst.iso
boot
```
[mini.iso](http://ftp.debian.org/debian/dists/unstable/main/installer-amd64/current/images/netboot/gtk/)
```
linux16 $prefix/memdisk iso raw
initrd16 /boot/isos/mini.iso
boot
```
It worked on a DELL PC, but in VMware EFI mode and my HP laptop , it just freeze there. 

Since these two iso have lots of menu entries, I just don't want to manually write a cfg file with all the entries and loopback the iso to boot it.  Although I may use only one entry forever, it just doesn't feel right 😞... 

So is there a alternative of memdisk to boot iso file, and as easy as memdisk does the job?

**Comment by gitterliu** [comment]
Turns out after I set CSM to enable, the issue is gone.

**Comment by aguslr** [comment]
Welp! You closed this issue as I was writing this comment, so here it goes anyway, for future reference:

You're right, [MEMDISK](http://www.syslinux.org/archives/2012-September/018468.html) [doesn't](http://www.syslinux.org/archives/2012-June/018033.html) [support](http://www.syslinux.org/archives/2016-September/025375.html) [UEFI](https://wiki.archlinux.org/index.php/syslinux#Limitations_of_UEFI_Syslinux) and there is a [bug open for Syslinux](https://bugzilla.syslinux.org/show_bug.cgi?id=30) but nothing so far. The only option for now would be to [enable CSM](https://en.wikipedia.org/wiki/Unified_Extensible_Firmware_Interface#CSM_booting).
