### ISSUE TITLE
Bugfix Manjaro 

### ISSUE THREAD

**Issue by LordTaifleh** [aguslr/multibootusb#58]
the path of the kernel files have changed with the newest manjaro releases. the start scripts cannot find them and thus refuse to boot. changing the lines
`  linux (loop)/manjaro/boot/$boot_dir/manjaro $bootoptions`
and 
`  initrd (loop)/manjaro/boot/$boot_dir/manjaro.img`
 to
 ` linux (loop)/manjaro/boot/$boot_dir/vmlinuz $bootoptions`
`  initrd (loop)/manjaro/boot/$boot_dir/initramfs.img`
fixes the problems

**Comment by aguslr** [comment]
Thanks, @LordTaifleh! Fixed with 5564581.
