### ISSUE TITLE
pmagic 2015 fu.sqfs dailed

### ISSUE THREAD

**Issue by phillip-white-sociomantic** [aguslr/multibootusb#59]
I am trying to boot pmagic 2015. I copied the iso to `boot/ios`. Other distros seems to be working fine.

Errors:
```
losetup: /dev/loop252: No such file or directory
mount: /dev/loop252: can't read superblock
Mounting the fu.sqfs failed.
```

Which versions of pmagic have been tested? 2013 is the last free one available

And it's booting via UEFI

**Comment by aguslr** [comment]
Hello @phillip-white-sociomantic 

Yes, the tested version is the last free available one which is `pmagic_2013_08_01.iso`. In 9e956e0, I've added, to [the distro page](http://mbusb.aguslr.com/distros/parted.html), a note about this and a link to download the ISO.

**Comment by phillip-white-sociomantic** [comment]
yes that works, thanks
