### ISSUE TITLE
Kali Linux 2017.1 Doesnt Boot

### ISSUE THREAD

**Issue by No0n3Left** [aguslr/multibootusb#68]
Using multibootusb, Kali is detected, but it goes to a blank screen and does nothing. I am wondering what this `configfile /boot/grub/loopback.cfg` is refering too. Is this a file withing the iso image? All others seem to work (well, except DBaN, which also goes to a blank screen). Note, the computer is an EFI (not technically UEFI), mac book pro 2015, and it can boot the same image when dd'd to a drive. I am wondering if the different method with which the boot file works is to blame. I have also tried the instructions on https://wiki.archlinux.org/index.php/Multiboot_USB_drive#Kali_Linux, but these just say I need to load the kernel first (upon hitting the initrd line), as the kernel file is not actually in the location listed. I have tried to mount the kali image to find the kernel image, but have had trouble doing so on mac (unsupported filesystem), and arch linux.

**Comment by aguslr** [comment]
Hello @No0n3Left.

About DBAN, it uses [MEMDISK](http://www.syslinux.org/wiki/index.php?title=MEMDISK) to boot the ISO file, so it might not work with EFI unless [CSM](https://en.wikipedia.org/wiki/Unified_Extensible_Firmware_Interface#CSM) is enabled (see issue #56). However, testing it in a [virtual machine with QEMU and OVMF](http://www.tianocore.org/ovmf/) I haven't been able to make it work either, so YMMV.

For Kali Linux, you are right! It seems support for `loopback.cfg` is broken in the latest release. In 9652dd1, I've added the menu entries for Kali Linux 2017.1. You'll see two menu entries, the old auto-generated for `loopback.cfg` and a custom one that should work fine.

**Comment by No0n3Left** [comment]
@aguslr, I just was able to try this, and it seems to work better than the loopback.cfg, as it doesnt return to the previous menu upon selecting it. Still, it does not work. Upon selecting any of the menu entries, it says "Error: You need to load the kernel first". This seems to related to linux (loop)/live/vmlinuz $bootoptions not actually working, and when the line initrd (loop)/live/initrd.img is ran, there is not kernel actually loaded. I tried to redownload the kali iso and that did nothing. I am storing this all on an (I know its bad) MBR USB with a FAT16 (msdos) partition labeled as 0xEF (EFI System Label). One note is its being booted via grub legacy (yeah I should change the label) from rEFInd, as I could not get grub EFI to load the correct config.

**Comment by aguslr** [comment]
Hi @No0n3Left!

> it says "Error: You need to load the kernel first".

The kernel is definitely located in `/live/vmlinuz` inside the ISO so this cannot be the problem.

> One note is its being booted via grub legacy (yeah I should change the label) from rEFInd, as I could not get grub EFI to load the correct config.

You mean GRUB legacy is the bootloader actually reading the menu entries? That might explain why it cannot load the kernel since [GRUB 2 uses `linux`](https://www.gnu.org/software/grub/manual/grub.html#linux) while [GRUB legacy uses `kernel`](https://www.gnu.org/software/grub/manual/legacy/grub.html#kernel). But then again, how does it even manage to read the entries when [the format is totally different](https://wiki.archlinux.org/index.php/GRUB_Legacy#Converting_GRUB_Legacy.27s_config_file_to_the_new_format)?

**Comment by No0n3Left** [comment]
@aguslr Sorry about that, I got confused. It is using GRUB 2 not legacy. I meant it was using bios backward compatibility (labeled legacy in rEFInd) rather than using the EFI version of grub2.
