### ISSUE TITLE
Issue Grub for EFI

### ISSUE THREAD

**Issue by Huby1** [aguslr/multibootusb#7]
Hi, 

I have run the script (makeUSB.sh) against my USB token, it ran correctly until this line: 
**Installing GRUB for EFI on /dev/sdb... FAILED**

I don't understand why it does not complete successfully ...
Device is a 32Go usb token and has been formatted as Fat before running the script.

Many Thanks,

**Comment by aguslr** [comment]
Hi Huby1,

Thanks for pointing out that the script doesn't display any messages when it fails. I have just committed a new version that should display the output of the failing command. Please, pull these new changes and try again so you can see the output.

Either way, if it failed at that point, you're probably missing the `grub-efi-amd64-bin` package (or equivalent for your distribution).

**Comment by Tormen** [comment]
I actually ran into the same problem.
For me it was the problem that on openSUSE it is actually grub2-install and not grub-install... 

I guess the makeUSB.sh script should check first for grub2-install and only if it does not find it use grub-install as fallback...

**Comment by Huby1** [comment]
Hi all,

Thanks Aguslr for habing changed the script. And thank you Tormen for your comment as it is actually a good point. Does the script is calling grub install from the running OS or does it use the source downloaded from this GIThub ? My OS is an Ubuntu 14.01 64bits. 
Should I download a grub2 installation package ? 
Sorry if my questions are a bit confusted.. 
Many Thanks to all for your time to help improving this project.

**Comment by aguslr** [comment]
Hi again Huby1,

The script calls grub-install from the running OS, which is usually installed by default since most Linux distros use GRUB as the default bootloader.

However, as I mentioned before, to install GRUB for EFI, the package `grub-efi-amd64-bin` needs to be installed as it contains the required files (e.g. `/usr/lib/grub/x86_64-efi/modinfo.sh`). The script probably shouldn't exit if this fails since it should still work for non-EFI systems, so I have change it in 9907146a2404b87a1b43aa9d3f3c55c32c835137.

Tormen raises a good point as it seems some distros use `grub2-install` instead of `grub-install`. However, if this were the case, the script would have failed before this point as it checks for the availability of the binary before doing anything else.

**Comment by Huby1** [comment]
Hi aguslr,

Thanks for lighting up .. if the package **grub-efi-amd64-bin** is not installed in my system, it is probably because I am running a 32 bits ubuntu version .. so, if I force to install it, can it harm my running system ? 
here is the grub version I am actually running: **grub-install (GRUB) 2.02~beta2-9ubuntu1.12**
Is there a way to install it from the bin file to the USB token ? 

Many Thanks,

**Comment by aguslr** [comment]
Hey,

According to the [Ubuntu page](http://packages.ubuntu.com/trusty/grub-efi-amd64-bin) for package `grub-efi-amd64-bin`, there are packages both for 32 and 64 bits systems.

This package only has the binaries needed to configure GRUB to boot from EFI systems but **does not** change your system's GRUB configuration, unlike the packages `grub-efi-ia32` and `grub-efi-amd64` that do conflict with the default `grup-pc` package.

However, it's OK if you don't install this package as I have changed the code (9907146a2404b87a1b43aa9d3f3c55c32c835137) so it ignores this error and continues the process to install GRUB for BIOS. The only issue is that the USB drive won't be able to boot on EFI-only systems.

**Comment by Huby1** [comment]
Hey, 

Thanks for the details, I have just retried with the changes you you have done so far.. here are the results: 
- no more output after the failing command (regress ?)
- The script is still stopping at the command: **Installing GRUB for EFI on /dev/sdb... FAILED**

I will try the headache of the EFI compatibility. I mean once it will work normally.

Again thanks,

**Comment by aguslr** [comment]
Sorry Huby1, I forgot to mention that I did revert the previous commit that outputs everything by default and added instead an argument to log to a file, which is cleaner.

Try: `sudo ./makeUSB.sh --log <device>`. You should get a file called `makeUSB.log` with all the output.

**Comment by Huby1** [comment]
Good thing agulsr, also have  you found why the script stop at the daulty command ?

**Comment by aguslr** [comment]
> have you found why the script stop at the daulty command ?

Oops, sorry! Yes, I deleted the wrong line of code. Fixed it in 3e6f18816f3914ccf7abf37a71994f641940df3c.

**Comment by Huby1** [comment]
It is all good the script is running smooth now. I am going to no add the EFI compatibility to my stick and will try again the script.

Many Thanks

**Comment by Huby1** [comment]
Hi aguslr,
Regarding the EFI compatibility, it is resolved. I installed as you suggested the `grub-efi-amd64-bin` to my running system and it allowed the script to run without failure. 
I am booting correctly and get the grub menu from my stick. I tried using a kubuntu iso file I had on my machine. As an adjustment I just had just to set the iso file name to the fit with the name file used in /boot/grub/grub.d/kubuntu-live.cfg.
I am able to boot to live OS but unable to install from it the OS .. I still don't know why. The issue is possibly because Kubuntu see a mounted drive and can not unmount it .. 

Any Ideas would be appreciate anyway.. I would like to be able also to install from it .. 

Cheers,

**Comment by aguslr** [comment]
Hi Huby1,

> I am able to boot to live OS but unable to install from it the OS

Could you open a new issue for this with information regarding the version of Kubuntu, etc? Thanks.

> it allowed the script to run without failure.

As this seems to be working, I'll go ahead and close this issue.

**Comment by Huby1** [comment]
Yes sure, 
Again thanks,

**Comment by JaneSmith** [comment]
If anyone has the same trouble I did, for Fedora Silverblue 31 it's `grub2-efi-x64-modules` that needs to be installed.
