### ISSUE TITLE
install runs flawlessly, but booting (in real or with qemu) drops right into grub shell and does NOT show the any grub menu

### ISSUE THREAD

**Issue by Tormen** [aguslr/multibootusb#8]
Hi.

Not sure why, but my install using 

` ./makeUSB.sh /dev/sde

runs flawlessly, aka:
```
Are you sure you want to use /dev/sde? [y/N] y
THIS WILL DELETE ALL DATA ON THE DEVICE. Are you sure? [y/N] y
Removing partitions from /dev/sde... OK
Creating GUID Partition Table on /dev/sde... OK
Creating BIOS boot partition on /dev/sde... OK
Creating EFI System partition on /dev/sde... OK
Creating data partition on /dev/sde... OK
Creating hybrid MBR on /dev/sde... OK
Setting bootable flag on /dev/sde3... OK
Formatting BIOS boot partition on /dev/sde1... 1+0 records in
1+0 records out
512 bytes (512 B) copied, 0.00622472 s, 82.3 kB/s
OK
Formatting EFI System partition on /dev/sde2... OK
Formatting data partition as vfat on /dev/sde3... OK
Mounting EFI System partition on /mnt/MBU-EFI/... OK
Mounting data partition on /mnt/MBU-DATA/... OK
Installing GRUB for EFI on /dev/sde... Installing for x86_64-efi platform.
Installation finished. No error reported.
OK
Unmounting EFI System partition on /mnt/MBU-EFI/... OK
Installing GRUB for BIOS on /dev/sde... Installing for i386-pc platform.
Installation finished. No error reported.
OK
Installing fallback GRUB on /dev/sde3... Installing for i386-pc platform.
grub-install: warning: File system `fat' doesn't support embedding.
grub-install: warning: Embedding is not possible.  GRUB can only be installed in this setup by using blocklists.  However, blocklists are UNRELIABLE and their use is discouraged..
Installation finished. No error reported.
OK
Creating directories on /mnt/MBU-DATA/boot... OK
Copying files to /mnt/MBU-DATA/boot... OK
Unmounting data partition on /mnt/MBU-DATA/... OK
```

But when I try to use the stick, it does not show any grub-menu, but drops right into the grub-shell :(
I possess firm Linux knowledge, but am not a grub master.
So no real idea how to debug this. 
... especially as there is no error message.
... I tried "log" "syslog" in the grub shell to see the error message ... but there is no such commands ;)

I tried a "real boot" and the qemu test command:

`qemu-system-x86_64 -enable-kvm -localtime -m 2G -vga std -drive file=/dev/sde,cache=none,if=virtio`

Same result with both:

![screenshot_20161031_223821](https://cloud.githubusercontent.com/assets/5610196/19870839/939589ea-9fb2-11e6-85ec-44fc51589cb2.png)

**Comment by Tormen** [comment]
Hmm. I think it is related to my comment on #7 ... because I had to create a symlink "grub-install" to grub2-install ... and now I have 
`<data-partition>/boot/grub` AND `<data-partition>/boot/grub2` ...
which probably should not be...

**Comment by Tormen** [comment]
Dear Agus,

Thanks. The version 35a07a7 did not pick grub2-install, though ;)

/usr/src/packages/source/multibootusb % sudo which -a grub-install
/usr/sbin/grub-install
/usr/src/packages/source/multibootusb % sudo which -a grub2-install
/usr/sbin/grub2-install
/usr/src/packages/source/multibootusb % sudo ./makeUSB.sh -l /dev/sde ext4
Are you sure you want to use /dev/sde? [y/N] y
THIS WILL DELETE ALL DATA ON THE DEVICE. Are you sure? [y/N] y
Removing partitions from /dev/sde... OK
Creating GUID Partition Table on /dev/sde... OK
Creating BIOS boot partition on /dev/sde... OK
Creating EFI System partition on /dev/sde... OK
Creating data partition on /dev/sde... OK
Creating hybrid MBR on /dev/sde... OK
Setting bootable flag on /dev/sde3... OK
Formatting BIOS boot partition on /dev/sde1... OK
Formatting EFI System partition on /dev/sde2... OK
Formatting data partition as ext4 on /dev/sde3... OK
Mounting EFI System partition on /mnt/MBU-EFI/... OK
Mounting data partition on /mnt/MBU-DATA/... OK
Installing GRUB for EFI on /dev/sde... OK
Unmounting EFI System partition on /mnt/MBU-EFI/... OK
Installing GRUB for BIOS on /dev/sde... FAILED

And here the end of the log:

mount: /dev/sde2 mounted on /mnt/MBU-EFI.
mount: /dev/sde3 mounted on /mnt/MBU-DATA.
Installing for x86_64-efi platform.
Installation finished. No error reported.
umount: /mnt/MBU-EFI/ unmounted
Installing for i386-pc platform.
/usr/sbin/grub-install: warning: Attempting to install GRUB to a disk with multi
/usr/sbin/grub-install: warning: Embedding is not possible.  GRUB can only be in
/usr/sbin/grub-install: error: will not proceed with blocklists.


Tormen

**Comment by aguslr** [comment]
Hey Tormen,

It seems that, to get around that error, we have to use `grub-install --force`. Check commit 187302cce3b7807d6f33f42f0ee38f745cd2d70d.

By the way, I've changed the script so it doesn't install EFI by default. Therefore, if you want EFI compatibility, you'll need to run:

```
sudo ./makeUSB.sh --efi -l /dev/sde ext4
```
