### ISSUE TITLE
Issues while Installing OS from USB token

### ISSUE THREAD

**Issue by Huby1** [aguslr/multibootusb#9]
Hi All, 

Going forward after having successfully setup a USB token. I am using a kubuntu 16.04.1 64bits iso file for testing. 
1 - when trying to boot from the live iso installer menu, the system boot up correctly but the installation process does not go forward as it detect a mounted device (the usb token) as it can not be unmounted the process hang.

2- Selecting the menu **Installer ISOs** .. well it just go no where.. 

Hope the description are clear enough.. 
If you have any idea ..

**Comment by aguslr** [comment]
Hey Huby1,

This seems to be a known bug for Ubiquity, the Ubuntu installer. See [bug #1155216](https://bugs.launchpad.net/ubuntu/+source/ubiquity/+bug/1155216) at Launchpad.

As a workaround, they recommend opening a terminal in the Live environment and manually unmount the device with `sudo umount -lrf /isodevice` before launching the installation. I just tested it and it seems to work.

Strangely enough, this only seems to happen with Kubuntu, as other installations (e.g. for Ubuntu GNOME) seem to work fine, although they also use Ubiquity.

**Comment by Huby1** [comment]
Hey agulsr,

Ok so I have tested this solution, it effectivelly allow to proceed with the installation on the internal HD. 
But it seems to have some issue after booting where the grafical interface hang (mouse not always present and unable to move using the 'Tab' key).. 
Well this is far away from our multiboot projet. .. but was surprise to see thoses instability on a version that has already 6 month or so...
Again many thanks

**Comment by aguslr** [comment]
You're welcome, Huby1!

What you mention is indeed surprising seeing as it's supposed to be the stable release. On the other hand, I haven't had any problems with Ubuntu GNOME, which is the version I usually install, so I wonder if these are related to KDE.

I'll close this issue since, as you pointed out, this is far beyond the scope of this project.

Good luck.
