### ISSUE TITLE
Support for Solus

### ISSUE THREAD

**Issue by aguslr** [aguslr/multibootusb#99]
Substitutes issue #31.

More information:
- https://solus-project.com/
- irc://chat.freenode.net/#Solus-Dev
- https://www.reddit.com/r/SolusProject/
- https://twitter.com/SolusProject

Current issues:
- https://redd.it/5vzhi2
- probonopd/SystemImageKit#17

**Comment by probonopd** [comment]
In think we should ask Solus to provide a `loopback.cfg`.

**Comment by a1ive** [comment]
menuentry "solus 3.0 budgie from ISO" {
    set isofile="Solus-3-Budgie.iso"
    loopback loop (hd0,4)/$isofile
    linux (loop)/boot/kernel root=live:CDLABEL=SolusLiveBudgie iso-scan/filename=/$isofile ro rd.luks=0 rd.md=0 quiet splash rd.live.image
    initrd (loop)/boot/initrd.img
}

**Comment by aguslr** [comment]
@a1ive, well done! It works even with older ISOs. :smile:

I'd swear I tried before that combination of boot parameters and it didn't work but I guess I missed something. I'll add support with PR #229.
